# [entryPoints]
#   [entryPoints.web]
#     address = ":80"
#   [entryPoints.web.http]
#     [entryPoints.web.http.redirections]
#       [entryPoints.web.http.redirections.entryPoint]
#         to = "websecure"
#         scheme = "https"

#   [entryPoints.websecure]
#     address = ":443"

# [accessLog]

# [api]
# dashboard = true

# [providers]
#   [providers.docker]
#     exposedByDefault = false

# [certificatesResolvers.letsencrypt.acme]
#   email = "st122331@eait.asia"
#   storage = "/certificates/acme.json"
#   [certificatesResolvers.letsencrypt.acme.httpChallenge]
#     entryPoint = "web"

# traefik.dev.toml

# listen on port 80
[entryPoints]
  [entryPoints.web]
    address = ":80"

# Traefik dashboard over http
[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]

# containers are not discovered automatically
[providers]
  [providers.docker]
    exposedByDefault = false