version: "3"
services: 
   
    api:
        build:
            context: ./eticketing
            dockerfile: Dockerfile
  
        ports:
            - "8000:8000"
        volumes:
            - ./eticketing:/home/app