version: "3"
services: 

    traefik:
        image: traefik:v2.3
    
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        environment:
            - TRAEFIK_PROVIDERS_DOCKER=true


            - TRAEFIK_ENTRYPOINTS_web=true
            - TRAEFIK_ENTRYPOINTS_web_ADDRESS=:80

            - TRAEFIK_ENTRYPOINTS_websecure=true
            - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443


            - TRAEFIK_API_INSECURE=true

    web:
        build:
            context: ./eticketing
            dockerfile: Dockerfile

        labels:
            - "traefik.http.routers.api.rule=Host(`192.41.170.116,`192.41.170.117`)"
            - "traefik.http.routers.api.entrypoints=web"
            - "traefik.http.services.api.loadbalancer.server.port=3200"        
     
volumes: 
  eticketing-traefik-proxy: