version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  eticketing:
    depends_on:
      - postgres_db
    build:
      context: ./eticketing
      dockerfile: Dockerfile
    image: eticketing:v1
    environment:
      - PORT=8020
    env_file:
      - eticketing/.env
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eticketing.entrypoints=web,websecure"
      - "traefik.http.routers.eticketing.rule=Host(`sad2-a.cs.ait.ac.th`)"
      - "traefik.http.routers.eticketing.tls=true"
      - "traefik.http.routers.eticketing.tls.certresolver=lets-encrypt"
    networks:
      - internal
      - web
  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - eticketing/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  staticfiles:
      external: false
  postgres_data: