version: "3"
services:
   
    web:
        image: 127.0.0.1:5000/E-Ticketing-System
        build:
            context: .
            dockerfile: Dockerfile
  
        ports:
            - "8000:8000"
        volumes:
            - ./eticketing:/home/app