version: "3.7"
services:
  traefik:
        image: traefik:v2.3
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TRAEFIK_PROVIDERS_DOCKER=true
            - TRAEFIK_ENTRYPOINTS_web=true
            - TRAEFIK_ENTRYPOINTS_web_ADDRESS=:80
            - TRAEFIK_ENTRYPOINTS_websecure=true
            - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443
            - TRAEFIK_API_INSECURE=true
  eticketing:
    depends_on:
      - postgres_db
    build:
      context: ./eticketing
      dockerfile: Dockerfile
    image: eticketing:v1
    environment:
      - PORT=8020
    env_file:
      - eticketing/.env
    ports:
      - "8020:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
    labels:
        - "traefik.http.routers.django.rule=PathPrefix(`/`)"
        - "traefik.http.routers.django.entrypoints=web"
        - "traefik.http.services.django.loadbalancer.server.port=80"
  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - eticketing/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  staticfiles:
      external: false
  postgres_data:
#   redis_data: 
