version: "3.7"
services:
  traefik:
        build:
          context: ./eticketing
          dockerfile: Dockerfile.traefik
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "./traefik-public-certificates:/certificates"
        
  eticketing:
    depends_on:
      - postgres_db
    build:
      context: ./eticketing
      dockerfile: Dockerfile
    image: eticketing:v1
    environment:
      - PORT=8020
    env_file:
      - eticketing/.env
    ports:
      - "8020:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=PathPrefix(`/`)"
        - "traefik.http.routers.django.tls=true"
        - "traefik.http.routers.django.tls.certresolver=letsencrypt"
        - "traefik.http.services.django.loadbalancer.server.port=443"
  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - eticketing/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  staticfiles:
      external: false
  postgres_data:
  traefik-public-certificates:
#   redis_data: 
