version: "3.7"
services:
  eticketing:
    depends_on:
      - postgres_db
    build:
      context: ./eticketing
      dockerfile: Dockerfile
    image: eticketing:v1
    environment:
      - PORT=8020
    env_file:
      - eticketing/.env
    ports:
      - "8020:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.eticketing-secure.entrypoints=websecure"
      - "traefik.http.services.eticketing-secure.loadbalancer.server.port=443"
  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - eticketing/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  staticfiles:
      external: false
  postgres_data:
#   redis_data: 

networks:
  proxy:
      external: true