version: "3"
services: 
   
    api:
        build:
            context: ./app
            dockerfile: Dockerfile
  
        ports:
            - "8000:8000"
        volumes:
            - ./app:/home/app