version: "3"

services: 
   
    django:

        image: localhost:5000/eticketing/django:3.0.3
        deploy:  
          replicas: 3

          labels:
              - "traefik.http.routers.api.rule=Host(`192.41.170.116,`192.41.170.117`)"
              - "traefik.http.routers.api.entrypoints=web"
              - "traefik.http.services.api.loadbalancer.server.port=3200"     

volumes: 
  eticketing-swarm: